import './bootstrap'
import '../../node_modules/jquery/dist/jquery'
import '../../node_modules/slick-slider/slick/slick'
import '../../node_modules/slick-slider/slick/slick-theme.css'
import './custom'
